/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SoundsRouteImport } from "./routes/sounds"
import { Route as SetupRouteImport } from "./routes/setup"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as SchedulesRouteImport } from "./routes/schedules"
import { Route as ProfilesRouteImport } from "./routes/profiles"
import { Route as IndexRouteImport } from "./routes/index"

const SoundsRoute = SoundsRouteImport.update({
  id: "/sounds",
  path: "/sounds",
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: "/schedules",
  path: "/schedules",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/profiles": typeof ProfilesRoute
  "/schedules": typeof SchedulesRoute
  "/settings": typeof SettingsRoute
  "/setup": typeof SetupRoute
  "/sounds": typeof SoundsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/profiles": typeof ProfilesRoute
  "/schedules": typeof SchedulesRoute
  "/settings": typeof SettingsRoute
  "/setup": typeof SetupRoute
  "/sounds": typeof SoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/profiles": typeof ProfilesRoute
  "/schedules": typeof SchedulesRoute
  "/settings": typeof SettingsRoute
  "/setup": typeof SetupRoute
  "/sounds": typeof SoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/profiles"
    | "/schedules"
    | "/settings"
    | "/setup"
    | "/sounds"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/profiles" | "/schedules" | "/settings" | "/setup" | "/sounds"
  id:
    | "__root__"
    | "/"
    | "/profiles"
    | "/schedules"
    | "/settings"
    | "/setup"
    | "/sounds"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesRoute: typeof ProfilesRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SoundsRoute: typeof SoundsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sounds": {
      id: "/sounds"
      path: "/sounds"
      fullPath: "/sounds"
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/setup": {
      id: "/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/schedules": {
      id: "/schedules"
      path: "/schedules"
      fullPath: "/schedules"
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profiles": {
      id: "/profiles"
      path: "/profiles"
      fullPath: "/profiles"
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesRoute: ProfilesRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SoundsRoute: SoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
